class Pdf:
    def __init__(self, path: str) -> None: ...
    def is_encrypted(self) -> bool: ...
    def set_password(self, password: str) -> None: ...
    def redact_text(self, text: str) -> None: ...
    def highlight_text(self, text: str) -> None: ...
    def save(self, path: str) -> None: ...
